//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjectt
    {
        public int Id_Subject { get; set; }
        public string namee { get; set; }
        public Nullable<int> hour_hand { get; set; }
        public string Teacher { get; set; }
        public Nullable<int> maximum_students { get; set; }
    }
}
