//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Students
    {
        public int Id_User { get; set; }
        public string Namee { get; set; }
        public string Surname { get; set; }
        public string Dni { get; set; }
        public string Filee { get; set; }
        public string Subjects { get; set; }
    }
}
